// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32            `json:"id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Category  string           `json:"category"`
	Tags      []string         `json:"tags"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
